#!/usr/bin/env php
<?php

echo <<<'EOL'
<?php

/**
 * see : https://github.com/lyrixx/nothing/tree/tmp\n";
 * It works on my laptop: PHP 5.4, Linux
 *
 * Grégoire Pineau <lyrixx@lyrixx.info>
 */

EOL;

echo str_replace("<?php\n", '', file_get_contents(__DIR__.'/Runner.php'));

echo str_replace("<?php\n", '', file_get_contents(__DIR__.'/Solver.php'));

echo <<<'EOL'

$runner = new Runner();
$runner->run();

EOL;
